// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpygwakpksolprthcrqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxweWd3YWtwa3NvbHBydGhjcnF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMzYyNDAsImV4cCI6MjA2MDYxMjI0MH0.2pDgdgBuDPKnuAnLikd50SjX60mTpoCtvvzmI-_lkV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);